apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
      - name: quarkus
        image: vkebisco/quarkus-quarkus-jpa-resteasy-jvm
        ports:
        - containerPort: 8080      
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus
spec:
  selector:
    app: quarkus
  ports:
  - port: 8080
    targetPort: 8080